### PR TITLE
Fix failing CI checks

### LINKED ISSUE #64: Fix all build pipeline failures
Need to fix all issues that cause the CI pipeline to fail on the following steps:

- lint
- test
- build:code
- build:i18n
- build:electron

The goal is to ensure that the entire build pipeline passes successfully, without errors or warnings.

### PR DESCRIPTION
**Pull request by Vsevolod-Rusinskiy**
Entire build pipeline passes successfully

Close #64

### CODE REVIEW

File: packages/apps-config/src/endpoints/testing.ts [hunk 1]
```diff
@@ -87,7 +84,7 @@ export const testParaChains: Omit<EndpointOption, 'teleport'>[] = [
     providers: {
       'QF Network': 'wss://para-test.qfnetwork.xyz'
     },
-    text: 'QF Testnet Parachain (Paseo)',
```
Comment (khssnv) [inline packages/apps-config/src/endpoints/testing.ts:90]: Why?

Comment (Vsevolod-Rusinskiy) [reply packages/apps-config/src/endpoints/testing.ts:90]: The test at `packages/apps-config/src/endpoints/index.spec.ts:140-141` specifically checks that endpoint names should not contain the redundant word "Parachain" since all parachain endpoints are already categorized as such.

The test was failing with:

AssertionError: QF Testnet Parachain (Paseo) should not contain "Parachain" (redundant)

Comment (khssnv) [reply packages/apps-config/src/endpoints/testing.ts:90]: > all parachain endpoints are already categorized as such

Not true for our case where endpoints are categorized by network type (test networks, dev networks), not by relay (polkadot & parachains, kusama & parachains). What do you think?

Comment (Vsevolod-Rusinskiy) [reply packages/apps-config/src/endpoints/testing.ts:90]: I suggest we simply remove this check then. I’ve updated the code.

**Review by khssnv — DISMISSED** [review]

**Review by khssnv — APPROVED** [review]
